# Generated by Django 2.2 on 2019-10-15 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tracker',
            name='summary',
            field=models.CharField(max_length=100, verbose_name='Summary'),
        ),
    ]
